version: '3'
services:
    rasa:
      user: root
      build: 
        context: ./rasa/kommunalcampus-de
      volumes:
      - "./rasa/kommunalcampus-de:/app"
      ports: 
        - "12345:5005"
        # Server Port: 12345:5005
        # Local Port: 5005:5005
    # action_server:
    #   build: 
    #     context: ./rasa/kommunalcampus-de/actions
    #   volumes:
    #     - ./rasa/kommunalcampus-de/actions:/app/actions
    #     - ./rasa/kommunalcampus-de/data:/app/data
    #   ports:
    #     - 5055:5055
